# Generated by Django 6.0.7 on 2026-07-22 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='카테고리')),
                ('tags', models.CharField(blank=True, help_text='여러 태그는 쉼표로 구분하세요.', max_length=200, verbose_name='태그')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='중요 노트')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '개발노트',
                'verbose_name_plural': '개발노트',
                'ordering': ['-is_pinned', '-updated_at'],
            },
        ),
    ]
