# Generated by Django 6.0.7 on 2026-07-25 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('description', models.TextField(verbose_name='설명')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='마감일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL, verbose_name='출제자')),
            ],
            options={
                'verbose_name': '과제',
                'verbose_name_plural': '과제',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('mentor', '멘토'), ('mentee', '멘티')], default='mentee', max_length=10, verbose_name='역할')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '프로필',
                'verbose_name_plural': '프로필',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='수행 내용')),
                ('attachment', models.FileField(blank=True, upload_to='submissions/%Y/%m/', verbose_name='첨부파일')),
                ('status', models.CharField(choices=[('in_progress', '진행중'), ('completed', '완료')], default='in_progress', max_length=20, verbose_name='상태')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='제출일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment', verbose_name='과제')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='학생')),
            ],
            options={
                'verbose_name': '제출물',
                'verbose_name_plural': '제출물',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('assignment', 'student'), name='unique_submission_per_student')],
            },
        ),
    ]
