# Generated by Django 6.0.7 on 2026-07-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, help_text='문자 알림을 받을 번호입니다. 예: 01012345678', max_length=20, verbose_name='휴대폰 번호'),
        ),
    ]
